### PR TITLE
fix zram-device-list for multiple starts or stops in a row

### PR DESCRIPTION
**Pull request by mstormi**

### CODE REVIEW

**Comment by StuartIanNaylor** [comment]
Delete your fork and I will transfer the project to you.
No longer have interest but can not transfer when branches with same name exist

**Comment by mstormi** [comment]
Duh - this is how to get a new job these days :-)

@EliasGabrielsson @kaikreuzer I think it would make most sense to transfer that to the openhab user, wdyt?

**Comment by kaikreuzer** [comment]
I have no clue, what this is at all about and how it relates to openHAB, so I would need some more background before I can comment...

**Comment by EliasGabrielsson** [comment]
I don't think this should be part of the openHAB umbrella as it have _no relation_ to the openHAB software. 

In case of the usage in openHABian context this software makes no difference from other external software. As openHABian is mainly an integration product (i.e combining and configure software) no external dependencies are maintain in the openHABian repo and that make sense for this software as well. I don't see any issues with using this in openHABian but the maintenance need to be done externally, for example if you get the projects transferred to you @mstormi. 

Compare this with the Miflora-mqtt-daemon which is also integrated in openHABian but maintained externally.
https://github.com/ThomDietrich/miflora-mqtt-daemon

**Comment by mstormi** [comment]
Ok Stuart, sad you lost interest but I'll try to keep it alive. I've deleted my fork on Github so you can transfer yours.
best regards

**Comment by mstormi** [comment]
@StuartIanNaylor please transfer

**Comment by mstormi** [comment]
@StuartIanNaylor any reason that you didn't transfer yet ? do you read ?

**Comment by mstormi** [comment]
@StuartIanNaylor anything wrong or why don't you transfer this repo as you announced ?

**Pull request merged**
